version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: analytics_mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USERNAME:-user}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DATABASE_MONGO_NAME:-analytics}
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  
  backoffice:
    container_name: analytics_backoffice
    build:
      context: ./back-office
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./back-office:/app
      - /app/node_modules
    
  analytics-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: analytics_api
    env_file:
      - .env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - '3080:3080'
    depends_on:
      - mongodb
    